### ISSUE TITLE
Dropdown actions have some extra spaces

### ISSUE THREAD

**Issue by Walmtech** [stokie-ant/lcdsmartie-laz#1]
Thanks stokie-ant for this massive update - glad the original program has been breathed some new life! 

I was finding a lot of action were not working as expected then found the labels in the drop down to select
them are incorrect they have spaces in them where none should be e.g.  Goto Screen and Goto Theme have spaces 
which don't work taking out the spaces manually fixes this.

**Comment by stokie-ant** [comment]
Thanks for that. Hopefully it should work as expected now. You may need to change some other actions to the new strings in the dropdown
[New release added](https://github.com/stokie-ant/lcdsmartie-laz/releases/tag/5.5.3.0)

**Comment by Walmtech** [comment]
All Perfect for me now! Many Thanks.
