### ISSUE TITLE
Implement custom LCD size options?

### ISSUE THREAD

**Issue by doqfgc** [stokie-ant/lcdsmartie-laz#12]
Neat revival of an old project you got here.

I am the proud owner of a Matrix Orbital bitmap display, and for the most part LCD Smartie works with it using the matrix.dll driver in text mode. However, I haven't been able to use it to its full potential because there aren't any LCD sizes that fit this specific model (GLK19264 series). While the maximum LCD size is 4x40 characters, this display in text mode can do 7x27 characters and this isn't a size that's selectable. Rather than asking for this size to be added, I'm suggesting allowing for custom LCD sizes, allowing for both futureproofing and wider compatibility.

Unfortunately I'm not familiar with Lazarus, so implementing it myself and raising a pull request is not possible.

**Comment by stokie-ant** [comment]
Try the latest release for me and let me know how it goes as I'm unable to test on a real display. It does seem to work with desktop.dll

**Comment by doqfgc** [comment]
I can confirm the latest release works and looks great!

Fixed.
