### ISSUE TITLE
Release package missing images on theme?

### ISSUE THREAD

**Issue by limbo666** [stokie-ant/lcdsmartie-laz#13]
Not sure what is happening here...
I'm getting lot of messages when I'm trying the latest release package [[5.5.4.15](https://github.com/stokie-ant/lcdsmartie-laz/releases/tag/5.5.4.15)].
The program complains about missing files on images folder. 
![image](https://github.com/stokie-ant/lcdsmartie-laz/assets/331155/eeb2c370-65fc-45fa-b0bb-1d0700fe7bcd)
The missing image file names are: "small_arrow_left_upX.bmp" and "small_arrow_left_downX.bmp" where X is a number increasing from  5 to 6 to 7 etc.
Is this a bug?

**Comment by stokie-ant** [comment]
Sorry, I screwed up. Let me fix that

**Comment by stokie-ant** [comment]
New package uploaded
