### ISSUE TITLE
Desktop dll displays only three lines on a four line display selected.

### ISSUE THREAD

**Issue by limbo666** [stokie-ant/lcdsmartie-laz#14]
I have tested both 32bit and 64bit of desktop.dll with the latest exe provided.
The problem is visible on the followings screens: 
![desktop screen](https://github.com/stokie-ant/lcdsmartie-laz/assets/331155/07a2bb7d-5484-461a-bfa9-da5ad97898d9)
![desktop screen_32Bit](https://github.com/stokie-ant/lcdsmartie-laz/assets/331155/1f07bd65-e054-4aa8-9ced-c8be9d3cb9d1)
It seems that for some reason once LCD Smartie switches from the first screens to the next enabled screen the lines on desktop emulated screen are getting larger and the result is to lose one on the four lines (the lower line).

**Comment by limbo666** [comment]
And half an hour later I feel like a complete idiot since I can't reproduce the issue.

![image](https://github.com/stokie-ant/lcdsmartie-laz/assets/331155/ca55e173-f4f3-413f-8111-8ff47ebbbb88)
I just moved the LCD Smartie folder from my desktop to a different path on the disk with the very same configuration file. desktop.dll works just fine.

Please just give it a try from your side and verify that everything is working for you on 4x40 sized virtual display.
If so, we have to close this issue with no further investigation.
Sorry for bothering you.

**Comment by limbo666** [comment]
Oh dear... it's me again!
this happens when the virtual display is dragged with the mouse.
![desktop dll malfunction](https://github.com/stokie-ant/lcdsmartie-laz/assets/331155/b8be15ff-7b0f-4e5e-b84a-c0024fb28149)
So I guess it is easy to verify the issue existence.

**Comment by stokie-ant** [comment]
Awesome, I've been sat here for 30 mins trying to reproduce it. I've got an idea of what's going wrong I just need to find why

**Comment by stokie-ant** [comment]
Right, so the paintbox edges are sized and anchored to the 4 insides of the frame before its removed. Now when it wants to redraw, somewhere at a lower level it gets that there's no frame  but now assumes we have a window of the size with frames. If you follow me. I fixed that by manually specifying the paintbox size anyway. It's getting a a bit late for me here so I'll clean up something else I was working on and get another release up tomorrow

**Comment by limbo666** [comment]
Fixed on 5.5.4.21
