### ISSUE TITLE
Crash on screen copy function

### ISSUE THREAD

**Issue by limbo666** [stokie-ant/lcdsmartie-laz#15]
I'm heavily Using the "Copy to" "Move to" and "Swap with" buttons to manage my screens.
Lots of times I'm facing the crash report
![Untitled-1](https://github.com/stokie-ant/lcdsmartie-laz/assets/331155/0f0bf765-0eaf-40f3-8bc5-6ca7ddd3e9ff)
Indicated as ```Exception message  : Range check error```
[report.txt](https://github.com/stokie-ant/lcdsmartie-laz/files/12049903/report.txt)
After a short investigation I found that the problem is caused when the user is typing the number instead using the numerical UpDown control on the interface (bad habit). 
Suggestion: since these textboxes are accepting any character to be typed, it would be a good idea to prevent typing anything else than numeric values and update the variables   when a number is typed on the field

**Comment by stokie-ant** [comment]
Oh, that was silly. I'm fetching the index of the value not he actual value
I've changed them to spinners that can only accept numbers as it makes more sense anyway. you can still type directly if you wish

**Comment by limbo666** [comment]
Thank you for taking care of this...
BTW I have few suggestions to make for developments here and there on the program.
I would be great if we have a communication channel to exchange ideas. Let me know what is your preference. 
We can use the forums or whatever you think is convenient

**Comment by stokie-ant** [comment]
Suggestions are very welcome, I'll contact you on the LCDSmartie forum. That's probably the safest way
