### ISSUE TITLE
LCD_TCP_MINGW_DLL (64bit) under multiple instances gives false "Could not bind socket" error

### ISSUE THREAD

**Issue by limbo666** [stokie-ant/lcdsmartie-laz#18]
Working with multiple instances (just two for the moment) of LCD Smartie under the same executable folder by using the startup parameters  `-config config2.ini` to have different configuration files for each instance. I'm facing the following message when the second instance of  LCD Smartie starts:
"LCD Smartie
Could not bind socket" 
 ![image](https://github.com/stokie-ant/lcdsmartie-laz/assets/331155/1f9c9b59-d1d9-4f68-a790-5afde2d8e8fa)

Which is probably related to the communication type of the driver. I'm using in both cases WiFi connected LCDs with different IP's but under the same port.
Driver used is "LCD_TCP_MINGW_DLL.dll" [64bit one provided on [https://github.com/stokie-ant/lcdsmartie-laz/issues/7](url)].
In every case the communication is flawless and both LCDs are alive under their own configuration and LCD Smartie shows no other message after the above mentioned.

FYI The issue appears even when I try to use different folders for each instance, so it is not related with the program itself. Maybe is the driver.

Any solution to hide this error message or complete fix this issue on its root it would be highly appreciated,

**Comment by stokie-ant** [comment]
Possibly Remote display tab, listen for remote connections is turned on but same port for both instances

**Comment by limbo666** [comment]
You are absolutely right! 
You rock man.  
Thank you.
