### ISSUE TITLE
`$SysCPUUsage` only reports first core usage

### ISSUE THREAD

**Issue by rdoursenaud** [stokie-ant/lcdsmartie-laz#3]
`$SysCPUUsage` only reports the first core usage on multi-core system instead of the combined system usage as reported by the windows task manager.

**Comment by stokie-ant** [comment]
What OS are you using? I'm seeing this problem with windows 11 but not 7

**Comment by rdoursenaud** [comment]
Yes Windows 11, sorry for not mentioning it.
22H2 build 22621.1485 precisely.

**Comment by stokie-ant** [comment]
I've tried several different methods and it's a no go. Windows 11 is doing something stupid with CPU times. It's actually broken quite a bit of other software
task manager Vs HWMonitor Vs Libre Hardware Monitor

![Screenshot 2023-04-01 225217](https://user-images.githubusercontent.com/58473635/229315805-c6bebe83-6aab-4e3f-80bf-42d3f63c2b65.png)

I'll leave this issue open for now in case I do figure something out

**Comment by stokie-ant** [comment]
Hopefully that'll work for you now

**Comment by Rei444** [comment]
I have exactly the same problem with the CPU in Win11. 
I cannot see a new compiled version  to eliminate this problem.

**Comment by rdoursenaud** [comment]
Thanks you for trying.
Unfortunately, on my machine (CPU: AMD Ryzen 5950X) it always reports `0` now.

I also get some screen garbling that wasn't there before that end up crashing my Matrix Orbital GLK19264-7T-1U.
Looking at the patch, I believe the later might be correlated to the removed full screen redraws.

Finally, the main window seems to have been redesigned without the Setup and Hide buttons and I find that annoying.

![image](https://user-images.githubusercontent.com/1210367/231669432-a4db0e93-75dc-4b87-8808-b2f6534caa09.png)

**Comment by rdoursenaud** [comment]
FWIW HWiNFO64 reports data that is in the ballpark of the task manager (Different sampling interval I guess). I don't know which method they use to retrieve these though.

**Comment by stokie-ant** [comment]
Looks like the new issue was with the English counter names. I've done the coding now just running it overnight to test stability. I've also fixed the size issue covering the buttons. I'll take another look at the screen redraw code. I took it away after deciding it was quicker to stream complete screen updates rather than just update what has changed as modern computers can handle it. Maybe it's too quick

**Comment by rdoursenaud** [comment]
Thanks. Looking forward to testing it.

**Comment by stokie-ant** [comment]
New version done. Let me know if it works

**Comment by rdoursenaud** [comment]
Let's start with the positive: No more screen garbling and crash. Setup and Hide buttons visible again \o/

Unfortunately, $SysCPUUsage still reports a solid `0`.

**Comment by stokie-ant** [comment]
Did we get this sorted?

**Comment by rdoursenaud** [comment]
Yes! The binary you posted in #8 works like a charm.

Thank you.
