### ISSUE TITLE
LCD2USB

### ISSUE THREAD

**Issue by Rei444** [stokie-ant/lcdsmartie-laz#4]
Hi Dear,
i have a Smartie Display DLL from "http://www.lcdmodkit.com/lcd/U204FB-A3.html". Works fine under smartie "https://lcdsmartie.sourceforge.net/" version 5.4. 
If i load this Dispaly iin your software, i became the message "warning: DLL may not be compatible".

**Comment by stokie-ant** [comment]
Does it still work just with a warning?

**Comment by stokie-ant** [comment]
I've compiled from source and get the message "LCD2USB Display DLL V0.13" But I don't have the hardware to test it.
Here is 32 and 64 bit driver and libusb0.dll that its linked against. Copy libusb0.dll to the folder with the LCDSmartie.exe
[LCD2USB-smartie-a01.zip](https://github.com/stokie-ant/lcdsmartie-laz/files/11195522/LCD2USB-smartie-a01.zip)

**Comment by Rei444** [comment]
Works fine.
Thank you very much for your efforts.

**Comment by stokie-ant** [comment]
You're welcome
