### ISSUE TITLE
CPU stats are faulty 

### ISSUE THREAD

**Issue by limbo666** [stokie-ant/lcdsmartie-laz#5]
v.5.5.3.4
_$SysCPUUsage_ generates a large negative number on the screen which continually changing.
similarly 
_$Bar($SysCPUUsage,100,18)_ flashing On/Off

**Comment by stokie-ant** [comment]
Are you using a non English version of Windows?

**Comment by limbo666** [comment]
I'm on English version Win 11 64 bit but i have additional input language enabled, which shouldn't make any difference.
I tried two different systems. The result is the same.

**Comment by limbo666** [comment]
> I'm on English version Win 11 64 bit but i have additional input language enabled, which shouldn't make any difference. I tried two different systems. The result is the same.

U
