### ISSUE TITLE
Text fields are not recognizing foreign characters. 

### ISSUE THREAD

**Issue by limbo666** [stokie-ant/lcdsmartie-laz#7]
In my previous LCD Smartie installation I used plugins to display foreign characters  by creating custom character on their configuration file. e.g by using the Search and Replace plugin 

The textboxes on LCD SMARTIE was able to recognize the characters probably using UTF formatting. Now the these texts is not recognized thus, the connection with these plugins is "broken".

**Comment by stokie-ant** [comment]
I think I might have sorted this but can you give me an example of the characters that don't display properly so I can test them

**Comment by limbo666** [comment]
Tested on 5.5.3.6 again. Greek characters are not recognized
Way to replicate: 
Extract the dll from zip into LCD Smartie plugins folder.
Place the omit.ini to C: drive (that's shoudl be C:\omit.ini)
Use the following line in your configuration: `$dll(sandr,2,ΑΒΓΔΘΛΞΠΣΥΦΨΩ,)`

If this works this should display this should display **ΑΒΓΔΘΛΞΠΣΥΦΨΩ** on virtual display or your LCD screen, 
In my case a line of question marks is displayed.

![questionmarks](https://user-images.githubusercontent.com/331155/233645931-4f4dbbc9-11cd-46f4-95f6-162f7b493265.png)


[SEARCH AND REPLACE.zip](https://github.com/stokie-ant/lcdsmartie-laz/files/11295927/SEARCH.AND.REPLACE.zip)

**Comment by stokie-ant** [comment]
It seems the problem was with DNBridge.dll but the omit.ini you sent has no mapping for the characters ΑΒΓΔΘΛΞΠΣΥΦΨΩ so I quickly made some edits

![image_2023-04-22_025841003](https://user-images.githubusercontent.com/58473635/233755847-ad4b31ba-8592-4067-a9c9-0ac989f282f6.png)

My display has mappings for Σ and Ω but the virtual display doesn't so they show as 6 and 4. I have extended the virtual font set but not filled in the data so let me know if there is any that should be in there.

Try this out. Let me know if it works
[DNBridge_x32.zip](https://github.com/stokie-ant/lcdsmartie-laz/files/11300040/DNBridge_x32.zip)
[DNBridge_x64.zip](https://github.com/stokie-ant/lcdsmartie-laz/files/11300041/DNBridge_x64.zip)

**Comment by limbo666** [comment]
**Yes!** these DNBridge files are fixing the problem.  Now we have the expected result. (BTW the ini is correct, it works in pairs of Search and Replace and I have all the Greek letters assigned to their equivalent character or custom character).
**GREAT WORK - KEEP ON!**

**Comment by limbo666** [comment]
> 
Well It seems that I spoke too early.
The situation is still tricky and now I don't really know where problem lies.
While the new DNBrdge seems to solve the issue on the program interface and display correctly the characters  when I'm using physical display the result is different under the same system with the very same configuration.
Please note that the physical display can display these character (under the very same line) in old versions of LCD Smartie.

 Program:
![untitled](https://user-images.githubusercontent.com/331155/233787617-219c7de8-6f33-4ecf-a174-aec8be0d9f4b.PNG)

Actual Result:
![20230422_161734](https://user-images.githubusercontent.com/331155/233787646-bef569c4-fe0a-45ec-bca7-e92484f46aee.jpg)


Furthermore testing the same settings on my laptop the situations is completely different. Even on the program dispaly the result is not correct.
 ![Screenshot 2023-04-22 161506](https://user-images.githubusercontent.com/331155/233787709-bc6da4a1-3a3a-4d50-b162-520cf2bdbc94.png)

Any ideas?

**Comment by stokie-ant** [comment]
Lets see if we can narrow this down.
This smartie exe will output a debug.log for plugin loads and variable resolves.
Run it for the minimum time as the file will grow very fast
[LCDSmartie-dbg-x64.zip](https://github.com/stokie-ant/lcdsmartie-laz/files/11301728/LCDSmartie-dbg-x64.zip)

**Comment by limbo666** [comment]
I have used the dbg executable to get the logs and  I'm back with the results.
**First of all the issue with LCD Smartie hanging on my desktop PC (reported here https://github.com/stokie-ant/lcdsmartie-laz/issues/9) is gone with this executable.**

1. On my desktop PC the translation seems to be done correctly the characters are displayed as expected on program interface.
![image](https://user-images.githubusercontent.com/331155/233830301-f8fec6a4-cbe1-45c1-9371-27b671889b4f.png)
The log file is here: [debug1(desktop).log](https://github.com/stokie-ant/lcdsmartie-laz/files/11303257/debug1.desktop.log)
System specs:
![Desktop](https://user-images.githubusercontent.com/331155/233829951-b7b4e1f2-c88e-4dbb-a53f-055a1fc5fb72.png)

2. On my laptop the character translation still fails although I used the same settings and the same pieces of software.
![Screenshot 2023-04-23 120522](https://user-images.githubusercontent.com/331155/233830443-f174a353-a789-4569-985f-839a52178a01.png)
The log file is here: [debug2(laptop).log](https://github.com/stokie-ant/lcdsmartie-laz/files/11303263/debug2.laptop.log)
System specs:
![Laptop](https://user-images.githubusercontent.com/331155/233829960-a13264a4-9f6f-47af-90ae-7e3eef4fbf1c.png)

Unfortunately the I'm not able to verify that these characters are displayed correctly on LCD hardware since both display types (FTDI and WiFi based on ESP8266 μC) I have handy are not supported by the executable. (FYI the dll files are here:
[displays.zip](https://github.com/stokie-ant/lcdsmartie-laz/files/11303283/displays.zip))
Trying to use them I get warning messages about compatibility 

![not compatible Wireless](https://user-images.githubusercontent.com/331155/233830170-98672494-81fc-4912-920d-305b097d4a92.png) 
![not compatible FTDI](https://user-images.githubusercontent.com/331155/233830178-d346a889-992a-4296-964a-94b393d9bf8d.png)

**Comment by stokie-ant** [comment]
Sorry about the late reply. I've been really busy lately. I'll take a look and see if it could be some optimisation causing the issue. The incompatible dll message usually means smartie is 64 bit but the plugins is 32 bit. I'll see about changing the message to reflect that and I'll clone that repo and see about porting it to 64 bit

**Comment by stokie-ant** [comment]
From laptop.log
Param 1: ΑΒΓΔΘΛΞΠΣΥΦΨΩ
Param 2:
Result: ΑΒΓΔΘΛΞΠΣΥΦΨΩ

Obviously the plugin should have replied with custom char lines

From desktop.log
Result: $CustomChar(1,31,16,16,16,16,16,16,0)$Chr(176)$CustomChar(2,4,10,10,17,17,17,31,0)$Chr(158)$CustomChar(3,4,10,17,21,17,10,4,0)$Chr(131)$CustomChar(4,4,10,10,17,17,17,17,0)$Chr(132)$CustomChar(6,31,17,17,17,17,17,17,0)$Chr(134)$CustomChar(8,17,21,21,14,4,4,4,0)$Chr(136)$CustomChar(8,14,17,17,17,14,0,31,0)$Chr(136)$CustomChar(7,31,16,8,4,8,16,31,0)$Chr(135)

There might still be a problem with DNBridge so here is DNBridge.dll compiled with a different charset support. I don't know if that will make a difference. If not I'll have to have DNBridge dump the character bytes it is processing.

I've built LCD_TCP_MINGW_DLL 64 bit. It seems to work but I can't test it. Do you know where the FTDI_LCD.dll is from?

Lastly LCDSmartie.exe with the optimizations turned down a notch to see if that fixes your hang/crash
[DNBridge.zip](https://github.com/stokie-ant/lcdsmartie-laz/files/11523212/DNBridge.zip)
[LCD_TCP_MINGW_DLL_x64.zip](https://github.com/stokie-ant/lcdsmartie-laz/files/11523213/LCD_TCP_MINGW_DLL_x64.zip)
[LCDSmartie_exe.zip](https://github.com/stokie-ant/lcdsmartie-laz/files/11523214/LCDSmartie_exe.zip)

**Comment by limbo666** [comment]
Well this is surely a step forward.
While the virtual display give the correct result (which I believe means that LCD Smartie detects the characters and plugin functionality) 
![image](https://github.com/stokie-ant/lcdsmartie-laz/assets/331155/bc30008c-cc06-44d5-a552-b946a36c1351)
the physical display running under the [LCD_TCP_MINGW_DLL_x64.zip](https://github.com/stokie-ant/lcdsmartie-laz/files/11523213/LCD_TCP_MINGW_DLL_x64.zip) display plugin fails to display the characters.
![image](https://github.com/stokie-ant/lcdsmartie-laz/assets/331155/2db5bb26-8dfe-4a35-a68c-cdf5c09101a9)

Even the following simple custom characters calling are not displaying anything on the physical screen (while the LCD smarftie emulated screen displays the custom characters) 
$CustomChar(1,17,17,14,0,10,0,17,14)$Chr(176)
$CustomChar(1,17,17,14,0,10,0,17,14)$Chr(176)
$CustomChar(3,14,17,10,0,21,17,14,4)$Chr(131)
![image](https://github.com/stokie-ant/lcdsmartie-laz/assets/331155/28c3b697-edb1-44e0-b413-6cdfe70ac54a)

Any change to fix the plugin ?

**Comment by stokie-ant** [comment]
I think I know what's wrong here. There was some code in the display write procedure that wouldn't compile under lazarus. It mapped custom locations to a display dll defined location. LCD_TCP needs that mapping. Let me see what I can come up with to replace it

**Comment by stokie-ant** [comment]
Give this one a spin for me please
[LCDSmartie_exe.zip](https://github.com/stokie-ant/lcdsmartie-laz/files/11982850/LCDSmartie_exe.zip)

**Comment by limbo666** [comment]
I just tested the x64 flavor.
SUCCESS!
 ![image](https://github.com/stokie-ant/lcdsmartie-laz/assets/331155/3bde80f3-c6cf-458d-8d96-0f8fdc4e09ac)
 
 Thank you for you efforts. 
 Now i have to fix my sandr.dll since I just discovered a tiny bug on its functionalities :-)

**Comment by Trihy** [comment]
I couldnt resolve this yet 

<img width="362" height="314" alt="Image" src="https://github.com/user-attachments/assets/a494703e-d8bb-4fe9-b393-75576025aa6c" />

Also tried to do a custom plugin using FW3.5 and foreign characters only show an ? Tried many encodings, but no luck.
